{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "rproxy") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ dig "service" "type" "ClusterIP" $service }}
  {{- if $service.nginx.enabled }}
  clusterIP: {{ include "rproxy.service.ip" . }}
  {{- end }}
  ports:
    - port: {{ dig "service" "port" 8083 $service }}
      targetPort: 8083
      protocol: {{ dig "service" "protocol" "TCP" $service }}
      name: {{ $service.name }}
    {{- if $service.nginx.enabled }}
    - port: 80
      targetPort: 80
      protocol: TCP
      name: rproxy-nginx
    {{- end }}
  selector:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels.selector" . | nindent 4 }}
{{- if $service.coredns.enabled }}
{{- $corednsName := include "common.names.custom" (list . (printf "%s-coredns" $service.name)) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $corednsName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ dig "service" "type" "ClusterIP" $service }}
  clusterIP: {{ include "coredns.service.ip" . }}
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: coredns-tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: coredns-udp
  selector:
    app.kubernetes.io/service: coredns
    {{- include "common.labels.selector" . | nindent 4 }}
{{- end }}
