{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if not .Values.global.chartContext.isBuiltIn }}
{{- $service := include "common.service" (dict "ctx" . "service" "casdoor") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-init" $serviceName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-init" $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- $defaultUser := $service.admin.name | default "root" }}
  {{- $defaultPass := $service.admin.password | default (include "common.randomPassword" $service.name) }}
  {{- $defaultHtpasswd := htpasswd $defaultUser $defaultPass | trimPrefix (printf "%s:" $defaultUser) }}
  INIT_ADMIN_USER: {{ $defaultUser | b64enc | quote }}
  {{- $secretPass := "" }}
  {{- $secretHtpasswd := "" }}
  {{- with and $existingSecret $existingSecret.data }}
    {{- $secretPass = index $existingSecret.data "INIT_ADMIN_PASSWORD" }}
    {{- $secretHtpasswd = index $existingSecret.data "INIT_ADMIN_HTPASSWD" }}
  {{- end }}
  INIT_ADMIN_PASSWORD: {{ $secretPass | default (b64enc $defaultPass) | quote }}
  INIT_ADMIN_HTPASSWD: {{ $secretHtpasswd | default (b64enc $defaultHtpasswd) | quote }}
{{- end }}
