{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "service" "agenticflow" "global" .) | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ dig "service" "type" "ClusterIP" $service }}
  clusterIP: None
  ports:
    - port: {{ dig "service" "port" 7860 $service }}
      targetPort: 7860
      protocol: {{ dig "service" "protocol" "TCP" $service }}
      name: {{ $service.name }}
  selector:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels.selector" . | nindent 4 }}
