{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "service" "temporal" "global" .) | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $pgConfig := include "common.postgresql.config" (dict "service" $service "global" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  DB: {{ "postgres12" | b64enc | quote }}
  DBNAME: {{ $pgConfig.database | b64enc | quote }}
  DB_PORT: {{ $pgConfig.port | toString | b64enc |  quote }}
  POSTGRES_SEEDS: {{ $pgConfig.host | b64enc |  quote }}
  POSTGRES_USER: {{ $pgConfig.user | b64enc |  quote }}
  POSTGRES_PWD: {{ $pgConfig.password | b64enc |  quote }}
  VISIBILITY_DBNAME: {{ printf "%s_visibility" $pgConfig.database | b64enc | quote }}
  DEFAULT_NAMESPACE: {{ "default" | b64enc | quote }}
  DEFAULT_NAMESPACE_RETENTION: {{ "7d" | b64enc | quote }}
{{- if ne $pgConfig.sslmode "disable" }}
  POSTGRES_TLS_ENABLED: {{ "true" | b64enc | quote }}
  SQL_TLS_ENABLED: {{ "true" | b64enc | quote }}
  {{- if regexMatch ".*.rds.amazonaws.com$" $pgConfig.host }}
  POSTGRES_TLS_CA_FILE: "/etc/certs/aws-ca-bundle.pem"
  SQL_CA: "/etc/certs/aws-ca-bundle.pem"
  POSTGRES_TLS_DISABLE_HOST_VERIFICATION: {{ "true" | b64enc | quote }}
  SQL_HOST_VERIFICATION: {{ "true" | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-certs" $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
{{- $currentScope := . }}
{{- range $path, $_ := .Files.Glob "certificates/*" }}
{{- with $currentScope }}
{{- base $path | nindent 2 }}: {{ .Files.Get $path | b64enc }}
{{- end }}
{{- end }}
{{- end }}
