{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "temporal") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ dig "service" "type" "ClusterIP" $service }}
  ports:
    - port: {{ dig "service" "port" 7233 $service }}
      targetPort: 7233
      protocol: {{ dig "service" "protocol" "TCP" $service }}
      name: {{ $service.name }}
    {{- if $service.console.enabled }}
    - port: {{ dig "console" "service" "port" "8080" $service }}
      targetPort: 8080
      protocol: {{ dig "console" "service" "protocol" "TCP" $service }}
      name: console
    {{- end }}
  selector:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels.selector" . | nindent 4 }}
