{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "service" "portal" "global" .) | fromYaml }}
{{- $runnerSvc := include "common.service" (dict "service" "runner" "global" .) | fromYaml }}
{{- $rproxySvc := include "common.service" (dict "service" "rproxy" "global" .) | fromYaml }}
{{- $serverSvc := include "common.service" (dict "service" "server" "global" .) | fromYaml }}
{{- $temporalSvc := include "common.service" (dict "service" "temporal" "global" .) | fromYaml }}
{{- $registrySvc := include "common.service" (dict "service" "registry" "global" .) | fromYaml }}
{{- $labelStudioSvc := include "common.service" (dict "service" "labelStudio" "global" .) | fromYaml }}
{{- $xnetSvc := include "common.service" (dict "service" "xnet" "global" .) | fromYaml }}
{{- $ingressConfig := include "common.ingress.config" (dict "service" $service "global" .) | fromYaml }}
{{- if $ingressConfig.enabled }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $servicePort := dig "service" "port" 8090 $service }}
{{- $rproxySvcName := include "common.names.custom" (list . $rproxySvc.name) }}
{{- $rproxySvcPort := dig "service" "port" 8083 $rproxySvc }}
{{- $serverSvcName := include "common.names.custom" (list . $serverSvc.name) }}
{{- $serverSvcPort := dig "service" "port" 8080 $serverSvc }}
{{- $temporalSvcName := include "common.names.custom" (list . $temporalSvc.name) }}
{{- $temporalSvcPort := dig "console" "service" "port" "8080" $temporalSvc }}
{{- $registrySvcName := include "common.names.custom" (list . $registrySvc.name) }}
{{- $registrySvcPort := dig "console" "service" "port" "5000" $registrySvc }}
{{- $labelStudioSvcName := include "common.names.custom" (list . $labelStudioSvc.name) }}
{{- $labelStudioSvcPort := dig "console" "service" "port" "8002" $labelStudioSvc }}
{{- $xnetSvcName := include "common.names.custom" (list . $xnetSvc.name) }}
{{- $xnetSvcPort := dig "service" "port" 8097 $xnetSvc }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- if $service.labels }}
      {{- toYaml $service.labels | nindent 4 }}
    {{- else }}
      {{- include "common.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ include "common.endpoint.csghub" . | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/client-header-timeout: "900"
    nginx.ingress.kubernetes.io/client-body-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
    nginx.ingress.kubernetes.io/custom-http-errors: "404,502,503"
    nginx.ingress.kubernetes.io/proxy_intercept_errors: "on"
    nginx.ingress.kubernetes.io/default-backend: {{ include "common.names.custom" (list . "ingress-nginx-defaultbackend") }}
    {{- if not $runnerSvc.usePublicDomain }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/endpoint/" {
        {{- $suffix := include "common.domain.cluster" . }}
        {{- $fullSvcName := printf "%s.%s.svc.%s" $rproxySvcName .Release.Namespace $suffix }}
        proxy_pass http://{{ printf "%s:%v" $fullSvcName $rproxySvcPort }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_cookie_flags ~ nosecure samesite=lax;
      }
    {{- end }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/docs/(.*) /$1 break;
      rewrite ^/-/label-studio(/|$)(.*) /$2 break;
      rewrite ^/xnet/(.*) /$1 break;
    {{- if $service.annotations }}
      {{- toYaml $service.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className | default "nginx" }}
  {{- if $ingressConfig.tls.enabled }}
  tls:
    - hosts:
        - {{ include "common.domain.csghub" . }}
        {{- if $runnerSvc.usePublicDomain }}
        - {{ printf "*.%s" (include "common.domain.public" .) | quote }}
        {{- end }}
      secretName: {{ $ingressConfig.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ include "common.domain.csghub" . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            {{- else }}
              serviceName: {{ $serviceName }}
              servicePort:  {{ $servicePort }}
            {{- end }}
          - path: /api/
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $serverSvcName }}
                port:
                  number: {{ $serverSvcPort }}
            {{- else }}
              serviceName: {{ $serverSvcName }}
              servicePort: {{ $serverSvcPort }}
            {{- end }}
          - path: /(hf|csg|ms)/
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $serverSvcName }}
                port:
                  number: {{ $serverSvcPort }}
            {{- else }}
              serviceName: {{ $serverSvcName }}
              servicePort: {{ $serverSvcPort }}
            {{- end }}
          - path: /.*\.git(/.*)?$
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $serverSvcName }}
                port:
                  number: {{ $serverSvcPort }}
            {{- else }}
              serviceName: {{ $serverSvcName }}
              servicePort: {{ $serverSvcPort }}
            {{- end }}
          {{- if or (and $service.docs.host $service.docs.port) $service.docs.domain }}
          - path: /docs(.*)
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ include "common.names.custom" (list . "docs") }}
                port:
                  number: {{ $service.docs.port }}
            {{- else }}
              serviceName: {{ include "common.names.custom" (list . "docs") }}
              servicePort: {{ $service.docs.port }}
            {{- end }}
          {{- end }}
          - path: /xnet
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $xnetSvcName }}
                port:
                  number: {{ $xnetSvcPort }}
            {{- else }}
              serviceName: {{ $xnetSvcName }}
              servicePort: {{ $xnetSvcPort }}
            {{- end }}
          {{- if .Values.global.registry.enabled }}
          - path: /v2
            pathType: Prefix
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $registrySvcName }}
                port:
                  number: {{ $registrySvcPort }}
            {{- else }}
              serviceName: {{ $registrySvcName }}
              servicePort: {{ $registrySvcPort }}
            {{- end }}
          {{- end }}
          {{- if $temporalSvc.console.enabled }}
          - path: /-/temporal
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $temporalSvcName }}
                port:
                  number: {{ $temporalSvcPort }}
            {{- else }}
              serviceName: {{ $temporalSvcName }}
              servicePort: {{ $temporalSvcPort }}
            {{- end }}
          {{- end }}
          - path: /-/label-studio(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $labelStudioSvcName }}
                port:
                  number: {{ $labelStudioSvcPort }}
            {{- else }}
              serviceName: {{ $labelStudioSvcName }}
              servicePort: {{ $labelStudioSvcPort }}
            {{- end }}
    {{- if $runnerSvc.usePublicDomain }}
    - host: {{ printf "*.%s" (include "common.domain.public" .) | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $rproxySvcName }}
                port:
                  number: {{ $rproxySvcPort }}
            {{- else }}
              serviceName: {{ $rproxySvcName }}
              servicePort: {{ $rproxySvcPort }}
            {{- end }}
    {{- end }}
{{- end }}
