{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "memmachine.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "memmachine.labels" . | nindent 4 }}
{{- end -}}
