{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "labelStudio") | fromYaml }}
{{- $dataflowSvc := include "common.service" (dict "ctx" . "service" "dataflow") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $pgConfig := include "common.postgresql.config" (dict "ctx" . "service" $service) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
data:
  ## Dataflow configuration
  {{- if .Values.global.chartContext.isBuiltIn }}
  CSGHUB_ENDPOINT: {{ include "common.endpoint.csghub" . | quote }}
  LABEL_STUDIO_HOST: {{ printf "%s/-/label-studio" (include "common.endpoint.csghub" .) | quote }}
  {{- else }}
  CSGHUB_ENDPOINT: {{ .Values.externalUrl | quote }}
  LABEL_STUDIO_HOST: {{ include "common.endpoint.labelstudio" . | quote }}
  {{- end }}
  LABEL_STUDIO_PORT: {{ $service | dig "service" "port" 8002 | quote }}
  DJANGO_DB: "default"
  JSON_LOG: "1"
  POSTGRE_HOST: {{ $pgConfig.host | quote }}
  POSTGRE_PORT: {{ $pgConfig.port | quote }}
  POSTGRE_NAME: {{ $pgConfig.database | quote }}
  POSTGRE_USER: {{ $pgConfig.user | quote }}
  POSTGRE_PASSWORD: {{ $pgConfig.password | quote }}
  SSLMODE: {{ $pgConfig.sslmode | quote }}
