{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if .Values.global.mongo.enabled }}
{{- $service := include "common.service" (dict "ctx" . "service" "mongo") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $serviceName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- $user := $service.auth.user | default "root" }}
  MONGO_INITDB_ROOT_USERNAME: {{ $user | b64enc | quote }}
  {{- $defaultPass := $service.auth.password | default (include "common.randomPassword" $user) | b64enc }}
  {{- $secretPass := "" }}
  {{- with and $existingSecret $existingSecret.data }}
    {{- $secretPass = index $existingSecret.data "MONGO_INITDB_ROOT_PASSWORD" }}
  {{- end }}
  MONGO_INITDB_ROOT_PASSWORD: {{ $secretPass | default $defaultPass | quote }}
{{- end }}
