{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "service" "minio" "global" .) | fromYaml }}
{{- $ingressConfig := include "common.ingress.config" (dict "service" $service "global" .) | fromYaml }}
{{- if and .Values.global.objectStore.enabled $ingressConfig.enabled }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $minioPort := dig "service" "port" 9000 $service }}
{{- $minioConsolePort := dig "console" "service" "port" "9001" $service }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- if $service.labels }}
      {{- toYaml $service.labels | nindent 4 }}
    {{- else }}
      {{- include "common.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /console {
        return 301 /console/;
      }
    {{- if $service.console.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/console/(.*) /$1 break;
    {{- end }}
    {{- if $service.annotations }}
      {{- toYaml $service.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className | default "nginx" }}
  {{- if $ingressConfig.tls.enabled }}
  tls:
    - hosts:
        - {{ include "common.domain.minio" . }}
      secretName: {{ $ingressConfig.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ include "common.domain.minio" . }}
      http:
        paths:
          {{- if $service.console.enabled }}
          - path: /console(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $minioConsolePort }}
            {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $minioConsolePort }}
            {{- end }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $minioPort }}
            {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $minioPort }}
            {{- end }}
{{- end }}
