{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "accounting") | fromYaml }}
{{- $paymentSvc := include "common.service" (dict "ctx" . "service" "payment") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ dig "service" "type" "ClusterIP" $service }}
  ports:
    - port: {{ dig "service" "port" 8086 $service }}
      targetPort: 8086
      protocol: {{ dig "service" "protocol" "TCP" $service }}
      name: {{ $service.name }}
    {{- if eq .Values.global.edition "saas" }}
    - port: {{ dig "service" "port" 8090 $paymentSvc }}
      targetPort: 8090
      protocol: {{ dig "service" "protocol" "TCP" $paymentSvc }}
      name: {{ $paymentSvc.name }}
    {{- end }}
  selector:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels.selector" . | nindent 4 }}
