{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "prometheus") | fromYaml }}
{{- $gatewayConfig := include "common.gateway.config" (dict "ctx" . "service" $service) | fromYaml }}
{{- if and $gatewayConfig.enabled $service.gateway.basicAuth }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $serviceName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- $defaultUser := $service.gateway.basicAuth.username | default "prometheus" }}
  {{- $defaultPass := $service.gateway.basicAuth.password | default (include "common.randomPassword" $service.name) }}
  {{- $defaultHtpasswd := htpasswd $defaultUser $defaultPass }}
  {{- $secretHtpasswd := "" }}
  {{- with and $existingSecret $existingSecret.data }}
    {{- $secretHtpasswd = index $existingSecret.data "auth" }}
  {{- end }}
  auth: {{ $secretHtpasswd | default (b64enc $defaultHtpasswd) | quote }}
{{- end }}
