{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "aigateway") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ dig "service" "type" "ClusterIP" $service }}
  ports:
    {{- if $service.moderation.enabled }}
    - port: {{ dig "service" "port" 8089 $service.moderation }}
      targetPort: 8089
      protocol: {{ dig "service" "protocol" "TCP" $service.moderation }}
      name: {{ printf "%s-moderation" $service.name }}
    {{- end }}
    - port: {{ dig "service" "port" 8094 $service.aigateway }}
      targetPort: 8094
      protocol: {{ dig "service" "protocol" "TCP" $service.aigateway }}
      name: {{ printf "%s-aigateway" $service.name }}
  selector:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels.selector" . | nindent 4 }}
